### ISSUE TITLE
Typescript / Types

### ISSUE THREAD

**Issue by uncaught** [logux/core#23]
I'd like to know what your plans for typescript is? I've seen a twitter post somewhere that you were looking for a conversion tool for JSDoc to TS.

I've started creating some types for logux in my app. But it would make more sense if those types ended up in your repository directly so others can benefit, too.

Do you plan to migrate to TS? 
Or do you plan to just add `.d.ts`-files?

I could help with both types and typescript conversion. The important thing is that the types will be kept in sync with the JS if only `.d.ts`-files will be added.

**Comment by ai** [comment]
> Do you plan to migrate to TS?

Nope. I prefer to avoid compiling.

> Or do you plan to just add .d.ts-files?

Absolutely. My dream is to use TS 3.7 and generate types from JSDoc.

But I do not have time right now. Can you (as experienced TS-user) help me here?

**Comment by hcomnetworkers** [comment]
I don't know any tool that can generate the types from JSDoc, but your JSDoc makes it easy to create the types.

The trickier thing is the placement of generics, which JSDoc does not have. I will keep building the types as I need them so that I can see what generics make sense. 

For example I'd give the server.type-function the action as generic, so that I have type-safety on all properties on the action and also lock down the action's type:

```ts
interface GroupsAdd {
  type: 'groups/add';
  group: Group;
}

server.type<GroupsAdd>(
  'groups/add', //will show an error if I have a typo here
  {
    //...
    async process(_ctx, action) {
      await initGruops.push(action.group); //the group is of type Group here
    },
  },
);
```

By sharing the action-interfaces in a common library shared by the server and client, I can make sure that both sides talk about the same stuff.

**Comment by uncaught** [comment]
I don't know any tool that can generate the types from JSDoc, but your JSDoc makes it easy to create the types.

The trickier thing is the placement of generics, which JSDoc does not have. I will keep building the types as I need them so that I can see what generics make sense. 

For example I'd give the server.type-function the action as generic, so that I have type-safety on all properties on the action and also lock down the action's type:

```ts
interface GroupsAdd {
  type: 'groups/add';
  group: Group;
}

server.type<GroupsAdd>(
  'groups/add', //will show an error if I have a typo here
  {
    //...
    async process(_ctx, action) {
      await initGruops.push(action.group); //the group is of type Group here
    },
  },
);
```

By sharing the action-interfaces in a common library shared by the server and client, I can make sure that both sides talk about the same stuff.

**Comment by ai** [comment]
@uncaught 

> I don't know any tool that can generate the types from JSDoc

TypeScript! It can ready JSDoc for types and in 3.7 they added `.d.ts` generation.

> The trickier thing is the placement of generics, which JSDoc does not have.

Yeap, JSDoc can be 100% replacement. Can we combine them? Generate from JSDoc for simple cases and use manual types for trickier?

**Comment by uncaught** [comment]
I'm more or less done with my app, so for now these are all the types I needed:
https://github.com/uncaught/doko/blob/master/common/%40types/logux.d.ts

I'm not really a fan of JSDoc. A lot of types will be too generic, like `string` when it's actually just a few distinct constants.

So if you want to continue using JSDoc, then the types will become out of date. And then the whole point of type-safety is gone.

Have you worked with TS before? I don't understand why compiling is a problem for you. With `ts-node` you won't notice a difference. Especially if you publish to NPM, all the compiling will be done upon publication and the apps using logux won't event get the plain typescript.

**Comment by ai** [comment]
>  I don't understand why compiling is a problem for you.

We need a way to use Logux directly from GitHub like `"@logux/core": "logux/core"` (without need to call sometime after install). It is useful to test fixes on production.

What if we will use approach from [my Storeon](https://github.com/storeon/storeon)? We could have separated `.d.ts` file and run TS on CI to check that current code (and tests) with this types to check that types are accurate.

The question is how to use TS types in Documentation.js.

**Comment by ai** [comment]
Logux got types. I am planning to release it today.
