### ISSUE TITLE
Add userContext

### ISSUE THREAD

**Issue by ai** [logux/core#30]
We may have some context of the user, like language. It should be synchronized with `connect` message.

**Comment by polemius** [comment]
I would like to implement this feature. Could you please provide more details?

**Comment by ai** [comment]
This issue was created to solve question number 1 from this question https://gitter.im/logux/logux?at=5e93679e3a85536c4325e719

We need to add options like:

```js
new Client({
  userId,
  token,
  userContext: {
    locale
  }
})
```

To start this issue, you need to suggest protocol and API changes.
