### ISSUE TITLE
nanoevents@7 in core vs nanoevents@8 in server/client

### ISSUE THREAD

**Issue by erictheswift** [logux/core#54]
Hey!
I see latest versions of `logux/server` and `logux/client` packages already use `"nanoevents": "^8.0.0"`
while logux/core@0.8.5 still has `"nanoevents": "^7.0.1"` dep.
As a result there can be multiple nanoevent versions in runtime.
It is minor, but anyway:
Is it intentional / are there any blockers to bumping logux/core nanoevents to 8?

**Comment by ai** [comment]
We need to drop Node.js 14 first in major release to move to NanoEvents 8.

**Comment by ai** [comment]
Yes, the difference between 7 and 8 is small. You can override it.
