### ISSUE TITLE
Export `LogStore`?

### ISSUE THREAD

**Issue by nichoth** [logux/core#57]
I see [in logux/client](https://github.com/logux/client/blob/2cc52842389db43ee73fbcaaee1da0d15ad005e0/indexed-store/index.d.ts#L1), you import `LogStore`:
```js
import { LogStore } from '@logux/core'
```

But I don't see `LogStore` exported here. It should be in [index.js](https://github.com/logux/core/blob/main/index.js)? Or am I missing something?

**Comment by ai** [comment]
It can be imported only to TS files because it is not real JS export, but just a type (technically, abstract class)

https://github.com/logux/core/blob/next/log/index.d.ts#L151
